name: schedules
description: Manage recurring events with ease.
version: 0.0.1
repository: https://github.com/andyhorn/schedules

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
